MA-23420-3 Update the imx_image_process_defaults to ImageTest target
Since imx_image_process_defaults will control if imx_image_process
enabled in the .go file, so also add imx_image_process_defaults to the
ImageTest target to make it under this control.

This patch fixed below build error on
aosp_trout_arm64-nxp_stable-userdebug config:
error: vendor/nxp-opensource/imx/image_process/Android.bp:82:1: module
"ImageTest" variant "android_vendor_arm64_armv8-a_cortex-a53": depends
on disabled module "libimagepr
ocess"

Change-Id: I1f11490166f2ad6bf6bbcedc718a4e717023a6db
Signed-off-by: Haoran Wang <elven.wang@nxp.com>
Reviewed-on: http://androidsource.nxp.com/project/28029
Reviewed-by: Hui Fang <hui.fang@nxp.com>