MA-22752 Fix image_process build error with 32bit rootfs
. issue happened when building the image with command as below:
export IMX_BUILD_32BIT_64BIT_ROOTFS=true
lunch evk_8mm-ap2a-userdebug
./imx-make.sh -j16a
will meet error:
vendor/nxp-opensource/imx/image_process/ImageProcess.cpp:796:24: error:
invalid operand in inline asm: 'rev16 ${0:w}, ${0:w}'
. the error is caused by the inline assembly in c++,
this way may not be good for platform compatibility.
'rev16' will perform byte reversal on both the upper
and lower halfwords of a 32-bit integer.
. to fix the issue, use function 'Revert16BitEndian' to complete the reverse.

Change-Id: I75c7f81236477572cab2921db05c33096802c7bf
Signed-off-by: Anle Pan <anle.pan@nxp.com>
Reviewed-on: http://androidsource.nxp.com/project/25598
Reviewed-by: Hui Fang <hui.fang@nxp.com>